### ISSUE TITLE
AppCompat issue with ADOBE AIR SDK 24.0 despite your patched adt.jar & runtimeClasses.jar used.

### ISSUE THREAD

**Issue by appearance** [marpies/account-kit-ane#3]
Hi marpies,

I am appearance. This is with regard to appcompat issue with AIR SDK 24.  We have had a conversation on [adobe forum](https://forums.adobe.com/thread/2206903).

Below is the message I wrote on the forum:

Hi mar.pies​,

I created a file in my resources named "provider_paths.xml" and finally it compiled without error.
But when the app is launched and Activity is launched I got following error:

12-17 16:48:27.362 21469-21469/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: air.mazhar.testane.android, PID: 21469
                                                   java.lang.NoSuchFieldError: No static field AppCompatTheme of type [I in class Landroid/support/v7/appcompat/R$styleable; or its superclasses (declaration of 'android.support.v7.appcompat.R$styleable' appears in /data/app/air.mazhar.testane.android-1/base.apk)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:339)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at com.trendyworks.ane.SugarMaths.TestActivity.onCreate(TestActivity.java:16)
                                                       at android.app.Activity.performCreate(Activity.java:6010)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

Here's the xml for TestActivity (activity_test.xml):

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
   xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:fitsSystemWindows="true"
   tools:context="com.trendyworks.ane.SugarMaths.TestActivity">

  <android.support.design.widget.AppBarLayout
   android:layout_width="match_parent"
   android:layout_height="wrap_content"
   android:theme="@style/SM_AppTheme.AppBarOverlay">

  <android.support.v7.widget.Toolbar
   android:id="@+id/toolbar"
   android:layout_width="match_parent"
   android:layout_height="?attr/actionBarSize"
   android:background="?attr/colorPrimary"
   app:popupTheme="@style/SM_AppTheme.PopupOverlay"/>

  </android.support.design.widget.AppBarLayout>

  <include layout="@layout/content_test"/>

  <android.support.design.widget.FloatingActionButton
   android:id="@+id/fab"
   android:layout_width="wrap_content"
   android:layout_height="wrap_content"
   android:layout_gravity="bottom|end"
   android:layout_margin="@dimen/fab_margin"
   app:srcCompat="@android:drawable/ic_dialog_email"/>

</android.support.design.widget.CoordinatorLayout>
```

-------------------------------------------------------------------------------------------------
Here's the xml for fragment (content_test.xml):
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
   android:id="@+id/content_test"
   xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   xmlns:tools="http://schemas.android.com/tools"
   android:layout_width="match_parent"
   android:layout_height="match_parent"
   android:paddingBottom="@dimen/activity_vertical_margin"
   android:paddingLeft="@dimen/activity_horizontal_margin"
   android:paddingRight="@dimen/activity_horizontal_margin"
   android:paddingTop="@dimen/activity_vertical_margin"
   app:layout_behavior="@string/appbar_scrolling_view_behavior"
   tools:context="com.trendyworks.ane.SugarMaths.TestActivity"
   tools:showIn="@layout/activity_test">

  <TextView
   android:layout_width="match_parent"
   android:layout_height="wrap_content"
   android:textAppearance="?android:attr/textAppearanceLarge"
   android:text="@string/app_name"
   android:gravity="center"
   android:layout_centerInParent="true"
   android:textSize="30sp"
   android:textStyle="bold"
   />
</RelativeLayout>
```
-----------------------------------------------------------------------------------------

Here's the TestActivity.java:

```
package com.trendyworks.ane.SugarMaths;

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;

public class TestActivity extends AppCompatActivity {

   @Override
   protected void onCreate (Bundle savedInstanceState) {
        super.onCreate (savedInstanceState);
       setContentView (R.layout.activity_test);

       Toolbar toolbar = (Toolbar) findViewById (R.id.toolbar);
       setSupportActionBar (toolbar);

       FloatingActionButton fab = (FloatingActionButton) findViewById (R.id.fab);
       fab.setOnClickListener (new View.OnClickListener () {
             @Override
             public void onClick (View view) {
                 Snackbar.make (view, "Replace with your own action", Snackbar.LENGTH_LONG)
                      .setAction ("Action", null).show ();
                 }
            });
       }
}
```

--------------------------------------------------------------------------------

I have used your PATCHED AIR SDK 24.  I have bundled my ane with same sdk's adt command.

Kindly tell me what's causing this error.

Thank you.

**Comment by marpies** [comment]
Hi @appearance,

I'm not sure what your ANE does or needs in terms of dependencies so it's really difficult for me to say why it's not working. Did you manage to launch app with your ANE before or is it related to AIR 24? What version of AppCompat library are you using when packaging your ANE?

**Comment by appearance** [comment]
Hi @marpies ,

I have posted the entire code of my ANE above. It's just an empty activity.  I have posted above activity xml, fragment xml and code for the activity.java.  I am using patched AIR SDK 24.0 provided by you for bundling the ANE.  What version of AppCompat library is irrelevant for me as I am using your appcompat.ane and support.ane, design.ane and recyclerview.ane.  Can you try with your PATCHED AIR SDK 24.0 and sample ANE with above code and using your [android-dependency-anes.](https://github.com/marpies/android-dependency-anes).

Thank you.

**Comment by marpies** [comment]
Does your ANE work with AIR 23?

**Comment by appearance** [comment]
for AIR 23 also, I have used your patched adt.jar & runtimeClasses.jar (for AIR SDK 23.0) and used your "android-dependency-anes", but it gives same error.

(Note: My ane is nothing but one empty activity derived from AppCompatActivity.  The whole idea is to successfully include android-support-appcompat library and invoke AppCompatActivity activity.)

**Comment by marpies** [comment]
I don't see any errors when I create `TestActivity` that extends `AppCompatActivity`. I can launch the activity from within the ANE and it shows up fine. I didn't use your resources to simplify the process, here's my code:

```java
package com.marpies.ane.facebook.accountkit;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

public class TestActivity extends AppCompatActivity {

	@Override
	protected void onCreate (Bundle savedInstanceState) {
		super.onCreate (savedInstanceState);

		Log.d("ANE", "AppCompatActivity :: onCreate");
	}
}
```

I then launch the activity using:

```java
Intent intent = new Intent( context.getActivity().getApplicationContext(), TestActivity.class );
context.getActivity().startActivity( intent );
```

In the AndroidManifest, I specify the activity as follows:

```xml
<activity
    android:name="com.marpies.ane.facebook.accountkit.TestActivity"
    android:theme="@style/Theme.AppCompat.Light"
    android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" />
```

**Comment by appearance** [comment]
Hi marpies,

Thank you so much for your sample code. But, your activity doesn't even show an empty view.   Please try to assign some empty content to the TestActivity via xml (setContentView()) and see if it shows any view or it gives the same error what I got.  In fact, I request you to use the activity_test.xml that I used to duplicate the issue.  Im trying to find out what's causing this error. Please help me in this regard.

Thank you.

**Comment by marpies** [comment]
Hi @appearance,

If you can, send me your Android project for the ANE lib. You are using some resources that I don't have, so it's difficult to create the same example.

**Comment by appearance** [comment]
Hi marpies,

I have attached android project zip file (AppCompatTestANE.zip). Please let me know if you want Flex project too for the ANE. Though, you can create one easily.  Please note that GetSchoolInfoFunction will try to launch TestActivity (derived from AppCompatActivity).

Thank you.

[AppCompatTestANE.zip](https://github.com/marpies/account-kit-ane/files/665834/AppCompatTestANE.zip)

**Comment by marpies** [comment]
Hi @appearance,

It works fine for me.

You are probably packaging your Android resources incorrectly. See the [platform-android.xml](https://github.com/marpies/account-kit-ane/blob/master/build/platform-android.xml) and [build.xml](https://github.com/marpies/account-kit-ane/blob/master/build/build.xml#L159-L170) for sample on how to specify the resources and create the ANE package. In your case, the `packageName` will be either `com.trendyworks.ane.SugarMaths` or `com.trendyworks.ane`.

I'm closing the issue because it's not related to the AccountKit ANE.

![screenshot](https://cloud.githubusercontent.com/assets/6077555/21401767/cff7a06e-c7b5-11e6-84de-ca053a2121e7.png)

**Comment by appearance** [comment]
Hi marpies,
Thank you so much. Can you please upload the one which is working for you, including platform.xml and extension.xml? It will help a lot if you send the flex wrapper project for this test.  Your help is really appreciated. 
Thank you.

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 22, 2016 at 12:14 AM, marpies<notifications@github.com> wrote:   
Hi @appearance,

It works fine for me.

You are probably packaging your Android resources incorrectly. See the platform-android.xml and build.xml for sample on how to specify the resources. In your case, the packageName will be either com.trendyworks.ane.SugarMaths or com.trendyworks.ane.

**Comment by marpies** [comment]
Hi @appearance,

I simplified the API to just `init` function but other than that it's the same code.

[app_compat_test.zip](https://github.com/marpies/account-kit-ane/files/669946/app_compat_test.zip)

**Comment by appearance** [comment]
Hi @marpies ,

Thank you so much.  I tried with directly with "com.trendyworks.ane.appCompatTest.ane" from the zip file your have provided.  It's compiled by you only. But even with this I am getting following error at runtime (when I call AppCompatTest.init() function):

java.lang.NoSuchFieldError: No static field AppCompatTheme of type [I in class Landroid/support/v7/appcompat/R$styleable; or its superclasses (declaration of 'android.support.v7.appcompat.R$styleable' appears in /data/app/air.mazhar.testane.android-1/base.apk)
at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:339)
at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
at com.trendyworks.ane.SugarMaths.TestActivity.onCreate(TestActivity.java:16)
at android.app.Activity.performCreate(Activity.java:6010)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
at android.app.ActivityThread.access$800(ActivityThread.java:155)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by marpies** [comment]
Hi @appearance,

Strange but I haven't encountered this issue. What device / OS version are you testing on?

**Comment by appearance** [comment]
I am using MotoE2 (android ver.5.1)  and Xiaomi Mi-5 (android ver.6.01) for testing.  
I am using Adobe AnimateCC 2017 with AIR SDK 24.0 (Patch provided by you).
using on windows 10.

Would you suggest me anything to investigate further in this regard?

Thank you.

**Comment by marpies** [comment]
Do you include these extensions in your app?

```xml
<extensions>
    <extensionID>com.trendyworks.ane.appCompatTest</extensionID>
    <extensionID>com.marpies.ane.androidsupport.appcompat</extensionID>
    <extensionID>com.marpies.ane.androidsupport.design</extensionID>
    <extensionID>com.marpies.ane.androidsupport</extensionID>
</extensions>
```

Unfortunately, I don't have any good suggestions. Perhaps try to Google this issue if anything useful comes up.

**Comment by appearance** [comment]
Yes, I included all of those extensionIDs and also com.marpies.ane.androidsupport.recyclerview too.
Without including those extensionIDs, in fact, final APK will not be built.
