### ISSUE TITLE
AccountKit and Android Support 25.2.0 are not compatible with Android 4.x

### ISSUE THREAD

**Issue by dnikolaev** [marpies/account-kit-ane#5]
It doesn't work on Android 4.x devices. No crash logs, nothing.

So I have to use AccountKit and Android Support 24.0.0

**Comment by dnikolaev** [comment]
I've just found the solution for this bug.

You need to change the manifest additions for the application tag to match the following and use the MultiDexApplication:
```
<manifest android:installLocation="auto">
	<!-- PERMISSIONS -->

	<application android:name="android.support.multidex.MultiDexApplication">

		<!-- ACTIVITIES / RECEIVERS / SERVICES -->

	</application>
</manifest>
```

**Comment by marpies** [comment]
Thanks for the solution!
